version: 2
jobs:
    build:
        docker:
            - image: golang:latest
        environment:
            GO111MODULE: on
        working_directory: /go/src/github.com/ieee0824/cryptex
        steps:
            - checkout
            - run:
                name: check fmt
                command: |
                    if [ $(go fmt ./... | wc -l) -eq 0 ]; then
                        exit 0
                    fi
                    echo "Go fmt is not applied."
                    exit 1
            - run:
                name: run test
                command: |
                    go test ./...