version: 2
jobs:
    build:
        docker:
            - image: ieee0824/go-circleci-docker:1.9
        working_directory: /go/src/github.com/ieee0824/cryptex
        steps:
            - checkout
            - run:
                name: install packages
                command: |
                    glide i
            - run:
                name: check fmt
                command: |
                    if [ $(go fmt $(glide nv) | wc -l) -eq 0 ]; then
                        exit 0
                    fi
                    echo "Go fmt is not applied."
                    exit 1
            - run:
                name: run test
                command: |
                    go test $(glide nv)
